package uz.tsx.bot.enums;

public enum StateEnum {
    START,
    MY_ANNS,
    GET_USER_ANNS,
    ENTERED_NEW_PASS,
    LOGINED,
    ENTERED_ANN_TITLE,
    ENTERED_ANN_CATEGORY,
    ENTERED_ANN_REGION,
    ENTERED_ANN_DESCRIPTION,
    ENTERED_ANN_CURRENCY,
    ENTERED_ANN_PRICE,
    ENTERED_ANN_IMAGE,
    FINISH
}
